#!/usr/bin/env node
/*
 * Regenerate the ANTLR Lexer/Parser/Listener/Visitor for the Trino SQL grammar
 * and normalise the output for this project. Run via `pnpm gen:grammar`.
 *
 * Steps:
 *   1. Invoke antlr4ng from the grammar's own directory so the emitted files
 *      land flat in src/trino-lang/generated/ (antlr4ng mirrors the *input
 *      path* under -o; running with a bare filename keeps it flat).
 *   2. Patch SqlBaseListener.ts so its `antlr4ng` import is type-only. The
 *      installed antlr4ng (3.0.16) exports `ParseTreeListener` as a *type*, not
 *      a runtime value; the generated code imports it (and three siblings used
 *      only in type position) as values, which breaks ESM bundlers. Making the
 *      import type-only fixes the bundle without hand-editing semantics.
 *   3. Stamp the provenance/license + @ts-nocheck banner on every .ts file.
 *
 * The grammar (SqlBase.g4) and its output originate from trino-query-ui
 * (Apache-2.0); see the repo-root NOTICE file.
 */
import { spawnSync } from 'node:child_process';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const webDir = join(here, '..');
const langDir = join(webDir, 'src', 'trino-lang');
const genDir = join(langDir, 'generated');

const require = createRequire(import.meta.url);

// 1. Generate (flat output, run from the grammar directory).
const cli = require.resolve('antlr4ng-cli/index.js');
const result = spawnSync(
  process.execPath,
  [cli, '-Dlanguage=TypeScript', '-visitor', '-listener', '-o', 'generated', 'SqlBase.g4'],
  { cwd: langDir, stdio: 'inherit' },
);
if (result.status !== 0) {
  console.error('antlr4ng generation failed.');
  process.exit(result.status ?? 1);
}

// 2. Make the listener's antlr4ng import type-only (used only in type position).
const listenerFile = join(genDir, 'SqlBaseListener.ts');
let listener = await readFile(listenerFile, 'utf8');
listener = listener.replace(/import \{ ([^}]*) \} from "antlr4ng";/, (full, names) =>
  names.includes('ParseTreeListener') ? `import type { ${names} } from "antlr4ng";` : full,
);
await writeFile(listenerFile, listener, 'utf8');

// 3. Stamp the banner.
const BANNER = [
  '// @ts-nocheck',
  '// Forked from trino-query-ui (https://github.com/) — Apache License 2.0.',
  '// Generated by antlr4ng from src/trino-lang/SqlBase.g4. Do not edit by hand;',
  '// run `pnpm --filter @hue-fable/web gen:grammar` to regenerate. See repo-root NOTICE.',
  '// (Machine-generated ANTLR output: @ts-nocheck — excluded from strict TS / lint.)',
  '',
].join('\n');

const stamped = [];
for (const name of await readdir(genDir)) {
  if (!name.endsWith('.ts')) continue;
  const file = join(genDir, name);
  const body = await readFile(file, 'utf8');
  if (body.startsWith('// @ts-nocheck')) continue;
  await writeFile(file, BANNER + body, 'utf8');
  stamped.push(name);
}
console.log(stamped.length ? `Stamped: ${stamped.join(', ')}` : 'Banner already present.');
